# 1. Understanding Data Types in Python

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
result = 0
for i in range(100):
    result += i
print(result)

4950


A single integer in Python 3.4 actually contains four pieces:
- **ob_refcnt**, a reference count that helps Python silently handle memory allocation and deallocation.
- **ob_type**, which encodes the type of the variable.
- **ob_size**, which specifies the size of the following data members.
- **ob_digit**, which contains the actual integer value that we expect the Python variable to represent.

## A Python List Is More Than Just a List

In [6]:
L = list(range(10))
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int]

In [7]:
L2 = [str(c) for c in L]
[type(item) for item in L2]

[str, str, str, str, str, str, str, str, str, str]

In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Fixed-Type Arrays in Python

In [8]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating Arrays from Python Lists

In [9]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [11]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [12]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

In [13]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
# Create an array filled with a linear sequence starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.14668439, 0.38302606, 0.15816724],
       [0.35291937, 0.39500642, 0.7402313 ],
       [0.8780137 , 0.06137025, 0.03987225]])

In [19]:
# Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.23817786, -0.23925412, -0.37128555],
       [-1.00205325, -0.70001321, -1.32279944],
       [ 1.48603567, -1.77708346,  0.08850892]])

In [20]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 9, 1],
       [4, 9, 3],
       [6, 7, 6]])

In [21]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [23]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [24]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)