# The Basics of NumPy Arrays

- **Attributes of arrays:**
Determining the size, shape, memory consumption, and data types of arrays.
- **Indexing of arrays:**
Getting and setting the value of individual array elements.
- **Slicing of arrays:**
Getting and setting smaller subarrays within a larger array.
- **Reshaping of arrays:**
Changing the shape of a given array.
- **Joining and splitting of arrays:**
Combining multiple arrays into one, and splitting one array into many.

## NumPy Array Attributes

In [1]:
import numpy as np

np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [6]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


## Array Indexing: Accessing Single Elements

In [13]:
l = []
for i in range(x1.size):
  l.append(x1[i])

l

[5, 0, 3, 3, 7, 9]

## Array Slicing: Accessing Subarrays
- x[start:stop:step]
### One-dimensional subarrays

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5] # first five elements
x[5:] # elements after index 5
x[4:7] # middle subarray
x[::2] # every other element
x[1::2] # every other element, starting at index 1
x[::-1] # all elements, reversed
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

### Multidimensional subarrays

In [18]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[:2, :3] # two rows, three columns
x2[:3, ::2] # all rows, every other column
x2[::-1, ::-1]

### Accessing array rows and columns

In [20]:
x2[:, 0]# first column of x2
x2[0] # equivalent to x2[0, :]


array([3, 5, 2, 4])

### Subarrays as no-copy views

In [21]:
x2_sub = x2[:2, :2]
x2_sub

array([[3, 5],
       [7, 6]])

In [22]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [23]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Creating copies of arrays

In [24]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [25]:
x2_sub_copy[0, 0] = 42

In [26]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Reshaping of Arrays

In [27]:
grid = np.arange(1,10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [32]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [33]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [34]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting
### Concatenation of arrays

In [37]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [38]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [39]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [40]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [42]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays 
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [43]:
y = np.array([[99],
              [99]])

# horizontally stack the arrays
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

In [44]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [45]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
upper, lower = np.vsplit(grid, [2])
print(upper,'\n')
print(lower)

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]]


In [49]:
left, right = np.hsplit(grid, [2])
print(left,'\n')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
